FlipsideCrypto/arbitrum-models

models/silver/silver__traces.yml

Config change to disable test on the null_value

Arbitrium config change on the yml file

---

models/sources.yml

model is currently excluded from dbt job - please remove that exclusion if merged!

source change

---

README.md
dbt_project.yml
macros/tags/add_database_or_schema_tags.sql
macros/tags/snowflake_tagging.sql
models/sushi/sushi__dim_dex_pools.sql
models/sushi/sushi__dim_kashi_pairs.sql
models/sushi/sushi__ez_borrowing.sql
models/sushi/sushi__ez_lending.sql
models/sushi/sushi__ez_swaps.sql

1. Implemented Snowflake tags via Macros and Model configs
2. Set `UPDATE_SNOWFLAKE_TAGS: True` and updated `readme.md` accordingly
3. Need to run `dbt run-operation` after merge
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2699?atlOrigin=eyJpIjoiMjBkNWI3ZTUyN2M4NDI4YzkzNDliYzRiOTZkNzExMGYiLCJwIjoiaiJ9)

AN-2699/snowflake-tags-arbitrum

---

.github/workflows/dbt_docs_update.yml
.github/workflows/dbt_run_adhoc.yml
.github/workflows/dbt_run_api_feeder_table.yml
.github/workflows/dbt_run_dev_refresh.yml
.github/workflows/dbt_run_incremental.yml
.github/workflows/dbt_test.yml

1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)

AN-2756/env-var-update

---

models/sushi/sushi__dim_kashi_pairs.yml
models/sushi/sushi__ez_borrowing.yml
models/sushi/sushi__ez_lending.yml

1. Added `Deprecating soon` to core sushi model descriptions
2. Removed tests from applicable yml files

AN-2785/sushi-tests-arb

---

models/gold/core__dim_labels.sql
models/gold/core__ez_eth_transfers.sql
models/gold/core__ez_token_transfers.sql
models/gold/core__ez_token_transfers.yml
models/gold/core__fact_hourly_token_prices.sql
models/gold/core__fact_hourly_token_prices.yml
models/sources.yml
models/sushi/sushi__dim_dex_pools.sql
models/sushi/sushi__dim_kashi_pairs.sql
models/sushi/sushi__ez_borrowing.sql
models/sushi/sushi__ez_borrowing.yml
models/sushi/sushi__ez_lending.sql
models/sushi/sushi__ez_lending.yml
models/sushi/sushi__ez_swaps.sql
models/sushi/sushi__ez_swaps.yml

1. Added `core.fact_hourly_token_prices` built off `crosschain` and updated references accordingly
2. Disabled sushi models as part of deprecation process

AN-2944/arb-price-pivot

---

models/gold/core__ez_token_transfers.sql

Joined contracts to ez_token_transfers for improved decimals and symbols coverage

AN-3020/add-contracts

---

models/gold/core__dim_labels.yml

- adds `bridge` as a valid label type

add label type 'bridge'

---

models/silver/silver__blocks.sql
models/silver/silver__contracts.sql
models/silver/silver__logs.sql
models/silver/silver__traces.sql
models/silver/silver__traces_nitro.sql
models/silver/silver__transactions.sql
models/silver/silver__transfers.sql

- Update all models using `hex_to_int` using `public` or `ethereum.public` schema to `utils` schema
- Excludes models with `enabled = false`

AN-3306/swap-public-to-utils

---

models/silver/streamline/decoder/history/streamline__decode_logs_history_000000001_000800001.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_000800002_001600002.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_001600003_002400003.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_002400004_003200004.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_003200005_004000005.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_004000006_004800006.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_004800007_005600007.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_005600008_006400008.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_006400009_007200009.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_007200010_008000010.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_008000011_008800011.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_008800012_009600012.sql
models/silver/streamline/decoder/history/streamline__decode_logs_history_009600013_009999999.sql

Added decoded logs history files for backfill back to genesis block

AN-3551/decode-logs-backfill

---

models/bronze/api_udf/_retry_abis.sql
models/bronze/api_udf/bronze_api__contract_abis.sql
models/sources.yml

- adds logic to retry abis for popular contracts

retry popular abis

---

models/silver/nft/silver__complete_nft_sales.sql
models/silver/nft/silver__nft_transfers.sql

1. Cast erc1155 value as string

erc1155 fix

---

models/doc_descriptions/nft/nft_event_index.md
models/doc_descriptions/nft/nft_nft_from_address.md
models/doc_descriptions/nft/nft_nft_to_address.md
models/gold/nft/core__ez_nft_transfers.yml
models/gold/nft/nft__ez_nft_transfers.yml
models/silver/nft/silver__complete_nft_sales.sql
models/silver/nft/silver__treasure_sales.sql
models/silver/nft/silver__treasure_sales.yml

1. Add Treasure marketplace to Arbitrum 
2. Changed price join logic to use priority eth prices table for arb's ETH and WETH 
3. Correct nft transfers docs

An 3735/add treasure marketplace

---

.github/workflows/dbt_alter_gha_task.yml
.github/workflows/dbt_run_abi_refresh.yml
.github/workflows/dbt_run_alter_gha_task.yml
.github/workflows/dbt_run_full_observability.yml
.github/workflows/dbt_run_heal_models.yml
.github/workflows/dbt_run_operation_reorg.yml
.github/workflows/dbt_run_scheduled_curated.yml
.github/workflows/dbt_run_scheduled_non_realtime.yml
.github/workflows/dbt_run_streamline_chainhead.yml
.github/workflows/dbt_run_streamline_decoder.yml
.github/workflows/dbt_run_streamline_decoder_history.yml
.github/workflows/dbt_run_streamline_history_adhoc.yml
.github/workflows/dbt_test_daily.yml
.github/workflows/dbt_test_intraday.yml
.github/workflows/dbt_test_monthly.yml
.github/workflows/dbt_test_tasks.yml
data/github_actions__workflows.csv
dbt_project.yml
models/github_actions/github_actions__current_task_status.sql
models/github_actions/github_actions__current_task_status.yml
models/github_actions/github_actions__task_history.sql
models/github_actions/github_actions__task_performance.sql
models/github_actions/github_actions__task_schedule.sql
models/github_actions/github_actions__tasks.sql
models/sources.yml
packages.yml

- `dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`
- `dbt run -s livequery_models.deploy.marketplace.github --vars '{UPDATE_UDFS_AND_SPS: true}’ -t prod`
- `dbt seed -s github_actions__workflows`
- `dbt run -m models/github_actions --full-refresh`
- `dbt run-operation fsc_utils.create_gha_tasks --var '{"UPDATE_GHA_TASKS":True}`

An 4105/lq tasks

---

models/silver/defi/lending/dforce/silver__dforce_borrows.sql
models/silver/defi/lending/dforce/silver__dforce_deposits.sql
models/silver/defi/lending/dforce/silver__dforce_liquidations.sql
models/silver/defi/lending/dforce/silver__dforce_repayments.sql
models/silver/defi/lending/dforce/silver__dforce_withdraws.sql

will require `dbt run -m models/silver/defi/lending/dforce+ --full-refresh`

dforce-platform-name-quickfix

---

packages.yml

`dbt run -m models/github_actions`

number format

---

models/silver/defi/lending/lodestar/silver__lodestar_asset_details.sql
models/silver/defi/lending/lodestar/silver__lodestar_borrows.sql
models/silver/defi/lending/lodestar/silver__lodestar_repayments.sql
models/silver/defi/lending/lodestar/silver__lodestar_withdraws.sql

`dbt run -m models/silver/defi/lending/lodestar/silver__lodestar_asset_details.sql+ --full-refresh`

AN-4474/arb-lending-bugs

---

models/bronze/api_udf/bronze_api__contract_abis.sql
models/bronze/api_udf/bronze_api__token_reads.sql
models/silver/defi/bridge/hop/silver_bridge__hop_ammwrapper.sql
models/silver/defi/bridge/hop/silver_bridge__hop_l2canonicaltoken.sql
models/silver/defi/bridge/stargate/silver_bridge__stargate_createpool.sql
models/silver/defi/dex/balancer/silver_dex__balancer_pools.sql
models/silver/defi/dex/curve/silver_dex__curve_pools.sql
models/sources.yml
package-lock.yml
packages.yml

`dbt run -s livequery_models.deploy.core --vars '{DROP_UDFS_AND_SPS: true}' -t prod && dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`

vault-secrets

---

models/silver/protocol/vertex/silver__vertex_perps.sql
models/silver/protocol/vertex/silver__vertex_spot.sql

`dbt run -m models/silver/protocol/vertex/silver__vertex_spot.sql+ models/silver/protocol/vertex/silver__vertex_perps.sql+ --full-refresh`

vertex-usd-amount-calc-fix

---

models/gold/defi/lending/defi__ez_lending_liquidations.yml
models/silver/defi/lending/complete_lending/silver__complete_lending_borrows.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_deposits.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_flashloans.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_withdraws.sql

`dbt run --vars '{"HEAL_CURATED_MODEL":["comp","dforce","lodestar"]}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql `

AN-4680/comp-and-comp-fork-liq-fix 

---

models/doc_descriptions/transfers/arb_transfer_table_doc.md
models/doc_descriptions/transfers/evm_transfers_table_doc.md
models/gold/core/core__ez_native_transfers.yml
models/gold/core/core__ez_token_transfers.yml
models/gold/core/core__fact_token_transfers.yml

to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`

AN-4879/transfers-docs

---

models/gold/nft/nft__ez_nft_sales.yml
models/silver/nft/sales/silver__complete_nft_sales.sql
models/silver/nft/sales/silver__element_sales.sql
models/silver/nft/sales/silver__element_sales.yml
models/silver/nft/sales/silver__seaport_1_4_sales.sql
models/silver/nft/sales/silver__seaport_1_5_sales.sql
models/silver/nft/sales/silver__seaport_1_6_sales.sql
models/silver/nft/sales/silver__treasure_sales.sql

Add element marketplace to Arbitrum
`dbt run -m models/silver/nft/sales/silver__element_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODELS":["element"]}'`

An 5040/element arb

---

package-lock.yml
packages.yml

`dbt run -m models/github_actions`

Update fsc utils version

---

models/silver/defi/lending/aave/silver__aave_repayments.sql

`dbt run -m models/silver/protocols/aave/lending/silver__aave_repayments.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`

aave-repay-bug

---

models/silver/protocols/vertex/silver__vertex_collateral.sql
models/silver/protocols/vertex/silver__vertex_collateral.yml

`dbt run -m models/silver/protocols/vertex/silver__vertex_collateral.sql+ --full-refresh`

arb-vertex-collateral

---

models/silver/defi/lending/aave/silver__aave_flashloans.sql

`dbt run -m models/silver/defi/lending/aave/silver__aave_flashloans.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_flashloans.sql`

AN-5431/aave-flashloan-initiator-bug 

---

models/doc_descriptions/general/__overview__.md
models/doc_descriptions/vertex/vertex_column_docs.md
models/doc_descriptions/vertex/vertex_table_docs.md
models/gold/protocols/vertex/vertex__ez_money_markets.sql
models/gold/protocols/vertex/vertex__ez_money_markets.yml
models/silver/protocols/vertex/silver__vertex_money_markets.sql
models/silver/protocols/vertex/silver__vertex_money_markets.yml

`dbt run -m models/silver/protocols/vertex/silver__vertex_money_markets.sql+`

AN-5565/add-vertex-money-markets

---

models/silver/protocols/vertex/silver__vertex_staking.sql

`dbt run -m models/silver/protocols/vertex/silver__vertex_staking.sql+ --full-refresh`

AN-5360/add-new-vertex-staking-contract

---

.github/workflows/dbt_run_traces_fix.yml
models/silver/core/silver__fact_traces2.sql
models/silver/core/traces2_fix/silver__fact_traces2_fix.sql

1. fix the error logic for fact_traces2 and new data
2. add model to identify historical data that needs fixing
3. add workflow to run model in step 2
`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`

AN-5669/fix-traces-v2-arb 

---

models/silver/protocols/vertex/silver__vertex_collateral.sql

`dbt run -m models/silver/protocols/vertex/silver__vertex_collateral.sql --full-refresh`

add-wstETH-to-collateral 

---

models/silver/defi/dex/pancakeswap/silver_dex__pancakeswap_v3_swaps.sql

fix `token_in` and `token_out` logic.
dbt run -m models/silver/defi/dex/pancakeswap/silver_dex__pancakeswap_v3_swaps.sql --full-refresh && dbt run -m models/silver/defi/dex/silver_dex__complete_dex_swaps.sql --vars '{"HEAL_MODELS":"pancakeswap_v3"}'

pcsv3-swap-fix

---

models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
packages.yml

`dbt run -m main_package.prices.bronze.bronze__complete_token_asset_metadata main_package.prices.silver.silver__complete_token_asset_metadata main_package.prices.gold.price__ez_asset_metadata --full-refresh`

newly verified
